### ISSUE TITLE
user account request for EAGLE

### ISSUE THREAD

**Issue by dieterhorns** [jaschers/damspi#1]
requesting a user account may be problematic - is it possible to include at least parts of the data to get going?

**Comment by jaschers** [comment]
What exactly is the problem with requesting an EAGLE account?
It's certainly possible to upload parts of the EAGLE data but I'm not sure if we are allowed to do so. Also, it will be possible to calculate the fluxes of the IMBHs for different channels, cross sections and dark matter masses with the catalogue that will be uploaded on Zenodo, so no need for an EAGLE account for this specific case.

**Comment by dieterhorns** [comment]
Maybe it is better to give an explanation what can be done without an eagle account and what can not. I am just worried about the eagle people getting an extra and maybe unnecessary work load to approve the account requests (this is done manually).

**Comment by jaschers** [comment]
Agree. I'll update the ReadMe file soon.
